### ISSUE TITLE
在 Notion 处未添加封面时同步失败

### ISSUE THREAD

**Issue by GrassBlock1** [LetTTGACO/elog#104]
### 你当前使用的Elog版本

0.13.5

### Elog配置文件

```javascript
module.exports = {
  write: {
    platform: 'notion',
    yuque: {
      token: process.env.YUQUE_TOKEN,
      login: process.env.YUQUE_LOGIN,
      repo: process.env.YUQUE_REPO,
      onlyPublic: false,
      onlyPublished: true,
    },
    'yuque-pwd': {
      username: process.env.YUQUE_USERNAME,
      password: process.env.YUQUE_PASSWORD,
      login: process.env.YUQUE_LOGIN,
      repo: process.env.YUQUE_REPO,
      onlyPublic: false,
      onlyPublished: true,
    },
    notion: {
      token: process.env.NOTION_TOKEN,
      databaseId: process.env.NOTION_DATABASE_ID,
      filter: {property: 'status', select: {equals: '已发布'}, },
      catalog: {
        enable: true,
        property: "slug"
      }
    },
    feishu: {
      type: 'space',
      wikiId: process.env.FEISHU_WIKI_ID,
      folderToken: process.env.FEISHU_FOLDER_TOKEN,
      appId: process.env.FEISHU_APP_ID,
      appSecret: process.env.FEISHU_APP_SECRET,
    },
    flowus: {
      tablePageId: process.env.FLOWUS_TABLE_PAGE_ID,
      filter: false, // {property: 'status',value: '已发布'}
    }
  },
  deploy: {
    platform: 'local',
    local: {
      outputDir: './content/posts/',
      filename: 'title',
      catalog: true,
      format: 'markdown',
      frontMatter: {
        enable: true,
        exclude: ['status','urlname'],
      },
      formatExt: './elog/cover.js'
    },
    halo: {
      endpoint: process.env.HALO_ENDPOINT,
      token: process.env.HALO_TOKEN,
      policyName: process.env.HALO_POLICY_NAME,
      rowType: 'html',
      needUploadImage: true,
    },
    confluence: {
      user: process.env.CONFLUENCE_USER,
      password: process.env.WORDPRESS_PASSWORD,
      endpoint: process.env.WORDPRESS_ENDPOINT,
      spaceKey: process.env.CONFLUENCE_SPACE_KEY,
      rootPageId: process.env.CONFLUENCE_ROOT_PAGE_ID, // 可选
    },
    wordpress: {
      username: process.env.WORDPRESS_USERNAME,
      password: process.env.WORDPRESS_PASSWORD,
      endpoint: process.env.WORDPRESS_ENDPOINT,
    }
  },
  image: {
    enable: true,
    platform: 'local',
    local: {
      outputDir: './assets/img',
      prefixKey: '/img',
      pathFollowDoc: false,
      imagePathExt: './elog/image.js'
    },
    oss: {
      secretId: process.env.OSS_SECRET_ID,
      secretKey: process.env.OSS_SECRET_KEY,
      bucket: process.env.OSS_BUCKET,
      region: process.env.OSS_REGION,
      host: process.env.OSS_HOST,
      prefixKey: '',
    },
    cos: {
      secretId: process.env.COS_SECRET_ID,
      secretKey: process.env.COS_SECRET_KEY,
      bucket: process.env.COS_BUCKET,
      region: process.env.COS_REGION,
      host: process.env.COS_HOST,
      prefixKey: '',
    },
    qiniu: {
      secretId: process.env.QINIU_SECRET_ID,
      secretKey: process.env.QINIU_SECRET_KEY,
      bucket: process.env.QINIU_BUCKET,
      region: process.env.QINIU_REGION,
      host: process.env.QINIU_HOST,
      prefixKey: '',
    },
    upyun: {
      user: process.env.UPYUN_USER,
      password: process.env.UPYUN_PASSWORD,
      bucket: process.env.UPYUN_BUCKET,
      host: process.env.UPYUN_HOST,
      prefixKey: '',
    },
    github: {
      token: process.env.GITHUB_TOKEN,
      user: process.env.ELOG_GITHUB_USER,
      repo: process.env.ELOG_GITHUB_REPO,
      prefixKey: '',
    }
  }
}
```

### 发生了什么？

如题，如果在 Notion 新建页面的时候没有添加封面，elog 同步的时候会在下载封面这一步报错退出，添加封面后正常。

如果可能的话希望能添加一个判断，如果没有封面的情况下就跳过下载封面这一步。

### Elog错误日志

```shell
> @ sync /home/runner/work/lab-2024/lab-2024
> elog sync

环境变量  未指定env文件，将从系统环境变量中读取
注意      正在使用插件/拓展点: ./elog/cover.js，请遵循插件/拓展开发规范
注意      正在使用图片路径拓展点，请遵循拓展点注入规范
正在获取文档列表，请稍等...
(node:1645) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
文档总数  3
跳过下载  再次迁移到 Bitwarden
跳过下载  使用 Mix Space × Zeabur 搭建自己的个人空间（博客）
待下载数  1
开始下载文档...
下载文档 1/1   答独立博客自省问卷15题
已下载数  1
开始处理图片...
开始下载封面
/home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+shared@0.13.5/node_modules/@elog/shared/dist/index.js:270
  const indexPoundSign = originalUrl.indexOf("#");
                                     ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at cleanParameter (/home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+shared@0.13.5/node_modules/@elog/shared/dist/index.js:270:38)
    at getUrl (/home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+shared@0.13.5/node_modules/@elog/shared/dist/index.js:299:10)
    at ImageUploader.<anonymous> (/home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+plugin-image@0.13.5_proxy-agent@5.0.0/node_modules/@elog/plugin-image/dist/index.js:856:36)
    at Generator.next (<anonymous>)
    at /home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+plugin-image@0.13.5_proxy-agent@5.0.0/node_modules/@elog/plugin-image/dist/index.js:44:61
    at new Promise (<anonymous>)
    at __async (/home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+plugin-image@0.13.5_proxy-agent@5.0.0/node_modules/@elog/plugin-image/dist/index.js:28:10)
    at ImageUploader.uploadImageFromUrl (/home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+plugin-image@0.13.5_proxy-agent@5.0.0/node_modules/@elog/plugin-image/dist/index.js:854:12)
    at DeployLocal.format [as adapter] (/home/runner/work/lab-2024/lab-2024/elog/cover.js:18:39)
    at DeployLocal.<anonymous> (/home/runner/work/lab-2024/lab-2024/node_modules/.pnpm/@elog+deploy@0.13.5/node_modules/@elog/deploy/dist/index.js:197:36)

Node.js v21.7.3
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by LetTTGACO** [comment]
在 elog.format.js 文件中修改部分代码，只有存在封面图才进行封面图替换
<img width="809" alt="image" src="https://github.com/user-attachments/assets/f93b3aa0-c6dd-4423-8dd0-126aed89c9a4">

**Comment by LetTTGACO** [comment]
只改了这一个地方吗？这个报错信息很模糊，log 信息都没打印出来，不太好排查。

可以试试在.elog.env 文件中 添加
DEBUG=TRUE
获取更多报错信息看看

**Comment by GrassBlock1** [comment]
> 只改了这一个地方吗？这个报错信息很模糊，log 信息都没打印出来，不太好排查。
> 
> 可以试试在.elog.env 文件中 添加 DEBUG=TRUE 获取更多报错信息看看
是的，只修改了这一部分
尝试添加了 `DEBUG=TRUE` 结果和上面的相同：
![image](https://github.com/user-attachments/assets/e1ea7f5e-a66b-43b4-9510-42faa906103e)

**Comment by LetTTGACO** [comment]
不使用拓展点，也就是把 formatExt: cover.js 注销能正常使用吗？

**Comment by GrassBlock1** [comment]
> 不使用拓展点，也就是把 formatExt: cover.js 注销能正常使用吗？
可以。
![image](https://github.com/user-attachments/assets/ee33d3ca-2e45-48c2-8ffd-ca6dbd0653fd)

以及这是我修改以后的 `cover.js` 拓展插件，可能对排错有帮助：
https://bin.gb0.dev/upload/b2AXva

**Comment by LetTTGACO** [comment]
找到问题了，你的 cover.js 语法有问题，程序直接退出了
<img width="826" alt="image" src="https://github.com/user-attachments/assets/eff2dd95-4479-49a1-8b80-6e5c6e39ab84">

**Comment by GrassBlock1** [comment]
> 找到问题了，你的 cover.js 语法有问题，程序直接退出了

一时疏忽没注意，删掉一个 { 之后就好了。感谢！🙏
